/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.saikat.NotifyServer;

import java.io.File;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;

import app.saikat.ConfigurationManagement.ConfigurationManagerInstanceHandler;
import app.saikat.ConfigurationManagement.interfaces.ConfigurationManager;

@SpringBootApplication
public class App {

    public static void main(String[] args) throws IOException {

        SpringApplication.run(App.class, args);
    }


    @Bean
    public WebsocketConfigurations getConf() throws IOException {
        
        Gson gson = new GsonBuilder()
        .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
        .setPrettyPrinting()
        .serializeNulls()
        .create();

        File configFile = new File("NotifyServer.conf");
        ConfigurationManager configurationManager = 
            ConfigurationManagerInstanceHandler.createInstance(configFile, gson);

        
        return configurationManager.<WebsocketConfigurations>get("websocket")
            .orElseGet( () -> {
                WebsocketConfigurations conf = WebsocketConfigurations.getDefault();
                configurationManager.put("websocket", conf);
                    try {
                        configurationManager.syncConfigurations();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                return conf;
            });
    }

}
